app/models.py
from . import db
from flask_login import UserMixin
from . import login_manager
from werkzeug.security import generate_password_hash,check_password_hash

class User(UserMixin,db.Model):
    __tablename__='users'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(255),index = True)
    email= db.Column(db.String(255),unique = True, index = True)
    pass_secure = db.Column(db.String(100))
    pitches=db.relationship('Pitches',backref='user',lazy='dynamic')
    profile_pic_path= db.Column(db.String())
    code = db.Column(db.Integer)

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

class Pitches(db.Model):
    __tablename__='pitches'
    id = db.Column(db.Integer, primary_key=True)
    title=db.Column(db.String(250))
    description=db.Column(db.String(250))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    



class Coments(db.Model):
    __tablename__='coments'
    id=db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(250))
    comment= db.Column(db.String())
    # users=db.relationship('User',backref='role',lazy='dynamic')

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import Required
from wtforms import ValidationError
from ..models import Pitches

class Pitch(FlaskForm):
  title = StringField('Enter the Title', validators=[Required()])
  description= TextAreaField('Give brief description',validators=[Required()])
  submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from config import config_options
from flask_login import LoginManager
from flask_mail import Mail
from flask_uploads import UploadSet,configure_uploads,IMAGES

login_manager=LoginManager()
login_manager.session_protection='strong'
login_manager.login_view ='auth.login'
bootstrap = Bootstrap()
db =SQLAlchemy()
mail = Mail()
photos = UploadSet('photos',IMAGES)

def create_app(config_name):
    app = Flask(__name__)
    #app configurations
    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)

    #flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    
    #Registering the main blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    #Registering auth blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/authenticate')


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import  views,errors

app/main/views.py
from flask import render_template,url_for,request,abort,redirect
from flask_login import login_required
from . import main
from .forms import Pitch
from .. import db
from ..models import User,Pitches,Coments

@main.route('/')
def index():
  user = User.query.filter_by(username='uname').first()
  pitches = Pitches.query.all()
  title = 'Welcome to pitch'
  message = 'Cool pitches'
  return render_template('index.html',message = message,title= title,pitches = pitches, user=user)

@main.route('/user/<uname>',methods=['GET','POST'])
@login_required
def profile(uname):
  user = User.query.filter_by(username=uname).first()
  pitches=Pitches.query.filter_by(user_id=user.id)
  if user is None:
    abort(404)
  title = f'{user.username}'
  return render_template('profile/profile.html',title=title,user = user,pitches=pitches)

@main.route('/pitches/<uname>', methods=['GET','POST'])
@login_required
def pitches(uname):
  pitch_form = Pitch()
  user = User.query.filter_by(username = uname).first()
  if pitch_form.validate_on_submit():
    pitch = Pitches(title = pitch_form.title.data, description = pitch_form.description.data,user = user)
    db.session.add(pitch)
    db.session.commit()
    return redirect(url_for('main.index'))
  title='Pitches'
  return render_template('pitch.html',title=title,pitch_form=pitch_form)

app/templates/base.html
{%extends 'bootstrap/base.html'%}

{% block navbar %}
    {% include 'navbar.html' %}
  {% endblock %}
  {% block content%}
  {% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block styles %}
  {{ super() }}
  <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
  <link rel="stylesheet" href="{{url_for('static',filename='css/index.css') }}" type='text/css'>
{% endblock %}
<!-- {% import "macro.html" as macro %} -->
{%block content %}
<h1 class='text-center'>{{message}}</h1> <hr>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <label>Our Guests Now</label>
      <script type="text/javascript" src="//ra.revolvermaps.com/0/0/1.js?i=0jl8feyv9eq&amp;s=250&amp;m=0&amp;v=false&amp;r=false&amp;b=000000&amp;n=false&amp;c=ff0000" async="async"></script>
    </div>
    <div class="col-md-8">
      <h2>All Pitches</h2>
      <div class="row">
        {% for pitch in pitches %}
        <div class="col-sm-6">
          <ul class='list-unstyled '>
            <li class='style'>
              <h3 class=text-primary>{{pitch.title}}</h3>
              <h4>{{pitch.description}}</h4>
              <p>By: {{pitch.user.username}}</p>
              <a href="{{url_for('main.pitches',uname = current_user.username)}}"><button class='btn btn-primary'>Comment</button></a>
            </li> <hr> <br>
            </ul>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>


{% endblock %}

app/templates/macro.html
{% macro display_pitch(pitches) %}
  {% for pitch in pitches %}
  <h1>{{pitch.title}}</h1>
  <h3>{{pitch.description}}</h3>
  {% endfor%}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse sticky" role="navigation">
  <div class="container-fluid">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Home</a>
      </div>
      <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
            <li><a href="{{url_for('main.pitches',uname=current_user.username)}}">Add Pitch</a></li>
            <li style="color:white;padding:15px;">{{current_user.username}}</li>
            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
          </ul>
      </div>
  </div>
</div>

app/templates/pitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
<div class="row">
<div class="col-md-3"> </div>
<div class="col-md-6">

{{wtf.quick_form(pitch_form)}}

</div>
<div class="col-md-3"></div>
</div>
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block styles %}
  {{ super() }}
  <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
  <link rel="stylesheet" href="{{url_for('static',filename='./css/index.css') }}" type='text/css'>
{% endblock %}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
</div>
</div>
  <h2 class='text-primary text-center'>Your Pitches</h2>
  <div class="row">
    {% for pitch in pitches %}
    <div class="col-sm-6">
      <ul class='list-unstyled '>
        <li class=style>
          <h3 class=text-primary>{{pitch.title}}</h3>
          <h4>{{pitch.description}}</h4>
        </li> <hr> <br>
        </ul>
    </div>

    {% endfor %}
  </div>
{% endblock %}